### ISSUE TITLE
The HUD selector is displayed when using the physgun

### ISSUE THREAD

**Issue by FlorianLeChat** [Kefta/Weapon-Switcher-Skeleton#5]
If you manipulate an object with the physgun and use the scroll wheel to change the distance, then the hud of the selector is triggered (see screenshot below). This is pretty annoying and this problem doesn't exist with the default selector.

Steps to reproduce :
- Spawn a prop
- Take it with the physgun and change the distance with the wheel
- Here we go..

![image](https://user-images.githubusercontent.com/26360935/103577337-e1027500-4ed4-11eb-8214-a4ea6ed52be8.png)

**Comment by Kefta** [comment]
Oops forgot about these issues, I'll look today

**Comment by FlorianLeChat** [comment]
Dear Kefta, you'll never resolve my issue unfortunately. I hope you find peace where you are now, your scripts and addons have always been an inspiration to many of us across the communities for many years. **Your legacy will not be forgotten**. ❤️
